### ISSUE TITLE
Thank you for your great project. When will the training code be released

### ISSUE THREAD

**Issue by zhanghongyong123456** [neuralchen/ASMAGAN#3]
Thank you for your great project.
1. When will the training code be released.
2. I want to get more painters how do I do that, how do I make the training datasets, how much data do I need
3. Looking forward to your reply

**Comment by crenaudineau1** [comment]
+1

**Comment by NNNNAI** [comment]
Thanks for your attention, I am busy with AAAI right now, I will release the related code after AAAI.

**Comment by crenaudineau1** [comment]
Thanks you for your response, and congrats for your amazing works.

**Comment by NNNNAI** [comment]
Thanks, have a nice day.

**Comment by NNNNAI** [comment]
Training code have been realeased, check the readme for detail.
