### ISSUE TITLE
Can't download pre-trained model

### ISSUE THREAD

**Issue by namdn** [neuralchen/ASMAGAN#5]
Hi! Could you please check your pre-trained model. The follow links is no found. Thank you 
https://github.com/neuralchen/ASMAGAN/releases/download/v.1.0/ASMAfinal.zip

**Comment by NNNNAI** [comment]
Thanks for your attention to ours work. I have been fix the link in readme, you can download the model from here https://github.com/neuralchen/ASMAGAN/releases/download/v.1.1/ASMAfinal.zip

**Comment by namdn** [comment]
Thank you for sharing the model
I've just download and get the following error when running command:
"python main.py --mode test --cuda 0 --version ASMAfinal  --dataloader_workers 8   --testImgRoot ./bench/ --nodeName localhost --checkpoint 350000 --testScriptsName common_useage --specify_sytle -1"


loaded trained models ./train_logs/ASMAfinal/checkpoints/350000_Generator.pth...!
  0%|                                                                                                                                                                                   | 0/25 [02:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 266, in <module>
    tester.test()
  File "/media/namdn/data/Projects/AI painting/ASMAGAN/test_scripts/tester_common_useage.py", line 82, in test
    res, _ = Gen(content, condition_labels[i, 0, :])
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/namdn/data/Projects/AI painting/ASMAGAN/train_logs/ASMAfinal/scripts/Conditional_Generator_asm.py", line 116, in forward
    x2 = self.encoder1(input)
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/functional.py", line 1945, in instance_norm
    use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by Leei-w** [comment]
> 感谢您分享我刚刚下载的模型，并在运行命令时收到以下错误："python main.py --mode test --cuda 0 --version ASMAfinal --dataloader_workers 8 --testImgRoot ./bench/ --nodeName localhost --checkpoint 350000 --testScriptsName common_useage --specify_sytle -1"
> 
> 加载了经过训练的模型 ./train_logs/ASMAfinal/checkpoints/350000_Generator.pth...！ 0%| | 0/25 [02：02<?, ?it/s] Traceback （最近一次调用）：文件 "main.py"， 第 266行， 在tester.test（） 文件 "/media/namdn/data/Projects/AI painting/ASMAGAN/test_scripts/tester_common_useage.py"， 第 82 行， 在测试分辨率中， _ = Gen（内容， condition_labels[i， 0， ：]）文件 "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py"， 第 550 行，**呼叫** result = self.forward（*input， **kwargs） File "/media/namdn/data/Projects/AI painting/ASMAGAN/train_logs/ASMAfinal/scripts/Conditional_Generator_asm.py"， line 116， in forward x2 = self.encoder1（input） File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py"， 第 550 行， in **call** result = self.forward（*input， **kwargs） 文件"/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/container.py"，第 100 行，在向前输入 = module（input）文件 "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/module.py"，第 550 行，**调用**结果 = self.forward（*input， **kwargs）文件 "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py"， 第 49 行， in forward self.training or not self.track_running_stats， self.momentum， self.eps） File "/home/namdn/miniconda3/envs/ASMA/lib/python3.6/site-packages/torch/nn/functional.py"， line 1945， in instance_norm use_input_stats， momentum， eps， torch.backends.cudnn.enabled RuntimeError： cuDNN error： CUDNN_STATUS_EXECUTION_FAILED

same problem

**Comment by NNNNAI** [comment]
Sorry for the late respond ,did you follow the installation section in readme.md to build your environment? And what kind of GPU did you use.

**Comment by namdn** [comment]
Thank you for your responding. I've fixed this error. Thanks a lot.

**Comment by NNNNAI** [comment]
You are welcome, have a nice day.
